{
  "openapi": "3.1.0",
  "info": { "title": "empleados-api-node", "description": "", "version": "1.0.0" },
  "tags": [{ "name": "Employee" }, { "name": "Department" }],
  "paths": {
    "/login": {
      "post": {
        "summary": "Login",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": { "email": { "type": "string" }, "password": { "type": "string" } },
                "required": ["email", "password"]
              },
              "example": { "email": "larry48@gmail.com", "password": "qwerty" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": { "type": "integer" },
                        "email": { "type": "string" },
                        "name": { "type": "string" },
                        "token": { "type": "string" }
                      },
                      "required": ["id", "email", "name", "token"]
                    }
                  },
                  "required": ["data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "data": {
                        "id": 2,
                        "email": "larry48@gmail.com",
                        "name": "Larry",
                        "token": "/y3+tlfN1huGJryJvcHh6g=="
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Empty Body",
                    "value": { "error": "Email is required, Password is required" }
                  },
                  "2": {
                    "summary": "Exception: Password Mismatch",
                    "value": { "error": "Incorrect password" }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "User not found" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/employees": {
      "get": {
        "summary": "List employees",
        "deprecated": false,
        "description": "",
        "tags": ["Employee"],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number, default 1",
            "required": false,
            "example": "1",
            "schema": { "type": "integer" }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Page limit, default 10",
            "required": false,
            "example": "10",
            "schema": { "type": "integer" }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Sort ascending by: \"name\", \"lastName\", \"birthDate\" or \"deptName\"",
            "required": false,
            "example": "name",
            "schema": { "type": "string" }
          },
          {
            "name": "search",
            "in": "query",
            "description": "Text to search",
            "required": false,
            "example": "Smith",
            "schema": { "type": "string" }
          },
          {
            "name": "deptId",
            "in": "query",
            "description": "Department identifier",
            "required": false,
            "example": "122",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "200 OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": { "type": "integer" },
                          "name": { "type": "string" },
                          "lastName": { "type": "string" },
                          "birthDate": { "type": "string" },
                          "address": { "type": ["string", "null"] },
                          "phone": { "type": ["string", "null"] },
                          "department": { "$ref": "#/components/schemas/Department" }
                        },
                        "required": [
                          "department",
                          "id",
                          "name",
                          "lastName",
                          "birthDate",
                          "address",
                          "phone"
                        ]
                      }
                    }
                  },
                  "required": ["data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "data": [
                        {
                          "id": 3,
                          "department": {
                            "id": 3,
                            "name": "Sales",
                            "description": "Department of Sales"
                          },
                          "name": "George",
                          "lastName": "Hernandez",
                          "birthDate": "1990-01-01T00:00:00.000Z",
                          "address": "Patterson Street, 456",
                          "phone": "1234567890"
                        },
                        {
                          "id": 1,
                          "department": {
                            "id": 1,
                            "name": "Development",
                            "description": "Department of Development"
                          },
                          "name": "Jhon",
                          "lastName": "Doe",
                          "birthDate": "1990-01-01T00:00:00.000Z",
                          "address": "Nulla Street, 123",
                          "phone": "1234567890"
                        }
                      ]
                    }
                  },
                  "2": { "summary": "Success: No data", "value": { "data": [] } },
                  "3": {
                    "summary": "Success: Search Smith",
                    "value": {
                      "data": [
                        {
                          "id": 2,
                          "department": {
                            "id": 2,
                            "name": "Human Resources",
                            "description": "Department of Human Resources"
                          },
                          "name": "Mary",
                          "lastName": "Smith",
                          "birthDate": "1990-01-01T00:00:00.000Z",
                          "address": "Martin Street, 123",
                          "phone": "1234567890"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Invalid queries",
                    "value": {
                      "error": "page must be a number greater than 0, limit must be a number greater than 0, sort must be name, lastName, birthDate or deptName"
                    }
                  },
                  "2": {
                    "summary": "Exception: Invalid dpto. ID",
                    "value": { "error": "deptId must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Department not found" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      },
      "post": {
        "summary": "Create employee",
        "deprecated": false,
        "description": "",
        "tags": ["Employee"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": { "type": "string" },
                  "lastName": { "type": "string" },
                  "birthDate": { "type": "string" },
                  "address": { "type": "string" },
                  "phone": { "type": "string" },
                  "deptId": { "type": "integer" }
                },
                "required": ["name", "lastName", "birthDate", "deptId"]
              },
              "example": {
                "name": "Peter",
                "lastName": "McGlynn",
                "birthDate": "1997-12-01",
                "address": "id dolor",
                "deptId": 1
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": { "type": "string" },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": { "type": "integer" },
                        "name": { "type": "string" },
                        "lastName": { "type": "string" },
                        "birthDate": { "type": "string" },
                        "address": { "type": ["string", "null"] },
                        "phone": { "type": ["string", "null"] },
                        "department": { "$ref": "#/components/schemas/Department" }
                      },
                      "required": [
                        "department",
                        "id",
                        "name",
                        "lastName",
                        "birthDate",
                        "address",
                        "phone"
                      ]
                    }
                  },
                  "required": ["message", "data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "message": "Employee created successfully",
                      "data": {
                        "id": 5,
                        "department": {
                          "id": 1,
                          "name": "Development",
                          "description": "Department of Development"
                        },
                        "name": "Peter",
                        "lastName": "McGlynn",
                        "birthDate": "1997-12-01T00:00:00.000Z",
                        "address": "id dolor",
                        "phone": null
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Empty body",
                    "value": {
                      "error": "Name is required, Last name is required, Birth date is required, Department is required"
                    }
                  },
                  "2": {
                    "summary": "Exception: Invalid dept. ID",
                    "value": { "error": "Department must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "404 No dpto", "value": { "error": "Department not found" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      }
    },
    "/departments": {
      "get": {
        "summary": "List departments",
        "deprecated": false,
        "description": "",
        "tags": ["Department"],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number, default 1",
            "required": false,
            "example": "1",
            "schema": { "type": "integer" }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Page limit, default 10",
            "required": false,
            "example": "10",
            "schema": { "type": "integer" }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Sort ascending by: \"name\", \"description\"",
            "required": false,
            "example": "name",
            "schema": { "type": "string" }
          },
          {
            "name": "search",
            "in": "query",
            "description": "Text to search",
            "required": false,
            "example": "a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": { "$ref": "#/components/schemas/Department" }
                    }
                  },
                  "required": ["data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "data": [
                        {
                          "id": 1,
                          "name": "Development",
                          "description": "Department of Development"
                        },
                        {
                          "id": 2,
                          "name": "Human Resources",
                          "description": "Department of Human Resources"
                        },
                        { "id": 3, "name": "Sales", "description": "Department of Sales" },
                        { "id": 4, "name": "Marketing", "description": "Department of Marketing" }
                      ]
                    }
                  },
                  "2": { "summary": "Success: No data", "value": { "data": [] } },
                  "3": {
                    "summary": "Success: Page 1 and limit 2",
                    "value": {
                      "data": [
                        {
                          "id": 1,
                          "name": "Development",
                          "description": "Department of Development"
                        },
                        {
                          "id": 2,
                          "name": "Human Resources",
                          "description": "Department of Human Resources"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Invalid queries",
                    "value": {
                      "error": "page must be a number greater than 0, limit must be a number greater than 0, sort must be name or description, search must not be empty"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      },
      "post": {
        "summary": "Create department",
        "deprecated": false,
        "description": "",
        "tags": ["Department"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": { "name": { "type": "string" }, "description": { "type": "string" } },
                "required": ["name"]
              },
              "example": { "name": "Sales" }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": { "type": "string" },
                    "data": { "$ref": "#/components/schemas/Department" }
                  },
                  "required": ["message", "data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "message": "Department created successfully",
                      "data": { "id": 5, "name": "Sales", "description": null }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Without name",
                    "value": { "error": "Name is required" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      }
    },
    "/register": {
      "post": {
        "summary": "Register",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": { "type": "string" },
                  "email": { "type": "string" },
                  "password": { "type": "string" }
                },
                "required": ["name", "email", "password"]
              },
              "example": { "name": "Larry", "email": "larry48@gmail.com", "password": "qwerty" }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": { "type": "integer" },
                        "name": { "type": "string" },
                        "email": { "type": "string" },
                        "token": { "type": "string" }
                      },
                      "required": ["id", "name", "email", "token"]
                    }
                  },
                  "required": ["data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "data": {
                        "id": 2,
                        "name": "Larry",
                        "email": "larry48@gmail.com",
                        "token": "M4axzZBCfiOn5Il0rr9DMQ=="
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Empty Body",
                    "value": {
                      "error": "Email is required, Password is required, Name is required"
                    }
                  },
                  "2": {
                    "summary": "Exception: Double Email",
                    "value": { "error": "Email already exists" }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/departments/{deptId}": {
      "get": {
        "summary": "Get department",
        "deprecated": false,
        "description": "",
        "tags": ["Department"],
        "parameters": [
          {
            "name": "deptId",
            "in": "path",
            "description": "Department identifier",
            "required": true,
            "example": "1",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "data": { "$ref": "#/components/schemas/Department" } },
                  "required": ["data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "data": {
                        "id": 1,
                        "name": "Development",
                        "description": "Department of Development"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Invalid path",
                    "value": { "error": "Department must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Department not found" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      },
      "put": {
        "summary": "Update department",
        "deprecated": false,
        "description": "",
        "tags": ["Department"],
        "parameters": [
          {
            "name": "deptId",
            "in": "path",
            "description": "Department identifier",
            "required": true,
            "example": "1",
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": { "name": { "type": "string" }, "description": { "type": "string" } },
                "required": ["name"]
              },
              "example": { "name": "Finance" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": { "type": "string" },
                    "data": { "$ref": "#/components/schemas/Department" }
                  },
                  "required": ["message", "data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "message": "Department modified successfully",
                      "data": {
                        "id": 1,
                        "name": "Finance",
                        "description": "Department of Development"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Without name",
                    "value": { "error": "Name is required" }
                  },
                  "2": {
                    "summary": "Exception: Invalid path",
                    "value": { "error": "Department must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      },
      "delete": {
        "summary": "Delete department",
        "deprecated": false,
        "description": "",
        "tags": ["Department"],
        "parameters": [
          {
            "name": "deptId",
            "in": "path",
            "description": "Department identifier",
            "required": true,
            "example": "1",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "message": { "type": "string" } },
                  "required": ["message"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": { "message": "Department deleted successfully" }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Invalid path",
                    "value": { "error": "Department must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception",
                    "value": { "error": "Departamento no encontrado" }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      }
    },
    "/employees/{employeeId}": {
      "get": {
        "summary": "Get employee",
        "deprecated": false,
        "description": "",
        "tags": ["Employee"],
        "parameters": [
          {
            "name": "employeeId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": { "type": "integer" },
                        "name": { "type": "string" },
                        "lastName": { "type": "string" },
                        "birthDate": { "type": "string" },
                        "address": { "type": ["string", "null"] },
                        "phone": { "type": ["string", "null"] },
                        "department": { "$ref": "#/components/schemas/Department" }
                      },
                      "required": [
                        "department",
                        "id",
                        "name",
                        "lastName",
                        "birthDate",
                        "address",
                        "phone"
                      ]
                    }
                  },
                  "required": ["data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "data": {
                        "id": 2,
                        "department": {
                          "id": 2,
                          "name": "Human Resources",
                          "description": "Department of Human Resources"
                        },
                        "name": "Mary",
                        "lastName": "Smith",
                        "birthDate": "1990-01-01T00:00:00.000Z",
                        "address": "Martin Street, 123",
                        "phone": "1234567890"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Invalid path",
                    "value": { "error": "employee id must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Employee not found" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      },
      "put": {
        "summary": "Update employee",
        "deprecated": false,
        "description": "",
        "tags": ["Employee"],
        "parameters": [
          {
            "name": "employeeId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "5",
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": { "type": "string" },
                  "lastName": { "type": "string" },
                  "birthDate": { "type": "string" },
                  "address": { "type": "string" },
                  "phone": { "type": "string" },
                  "deptId": { "type": "integer" }
                },
                "required": ["name", "lastName", "birthDate", "deptId"]
              },
              "example": {
                "name": "German",
                "lastName": "Rodriguez",
                "birthDate": "1997-12-01",
                "deptId": 2
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": { "type": "string" },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": { "type": "integer" },
                        "name": { "type": "string" },
                        "lastName": { "type": "string" },
                        "birthDate": { "type": "string" },
                        "address": { "type": ["string", "null"] },
                        "phone": { "type": ["string", "null"] },
                        "department": { "$ref": "#/components/schemas/Department" }
                      },
                      "required": [
                        "department",
                        "id",
                        "name",
                        "lastName",
                        "birthDate",
                        "address",
                        "phone"
                      ]
                    }
                  },
                  "required": ["message", "data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "message": "Employee modified successfully",
                      "data": {
                        "id": 5,
                        "department": {
                          "id": 2,
                          "name": "Human Resources",
                          "description": "Department of Human Resources"
                        },
                        "name": "German",
                        "lastName": "Rodriguez",
                        "birthDate": "1997-12-01T00:00:00.000Z",
                        "address": "id dolor",
                        "phone": null
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400 No body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Empty body",
                    "value": {
                      "error": "Name is required, Last name is required, Birth date is required, Department is required"
                    }
                  },
                  "2": {
                    "summary": "Exception: Invalid dpto ID",
                    "value": { "error": "Department must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Dept. not found",
                    "value": { "error": "Department not found" }
                  },
                  "2": {
                    "summary": "Exception: Employee not found",
                    "value": { "error": "Employee not found" }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      },
      "delete": {
        "summary": "Delete employee",
        "deprecated": false,
        "description": "",
        "tags": ["Employee"],
        "parameters": [
          {
            "name": "employeeId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "5",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "message": { "type": "string" } },
                  "required": ["message"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": { "message": "Employee deleted successfully" }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Invalid path",
                    "value": { "error": "employee id must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Employee not found" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      }
    },
    "/departments/{deptId}/employees": {
      "get": {
        "summary": "Employees by dept",
        "deprecated": false,
        "description": "",
        "tags": ["Department"],
        "parameters": [
          {
            "name": "deptId",
            "in": "path",
            "description": "Department Identifier",
            "required": true,
            "example": "1",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": { "$ref": "#/components/schemas/Employee" }
                    }
                  },
                  "required": ["data"]
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "data": [
                        {
                          "id": 1,
                          "name": "Jhon",
                          "lastName": "Doe",
                          "birthDate": "1990-01-01T00:00:00.000Z",
                          "address": "Nulla Street, 123",
                          "phone": "1234567890"
                        }
                      ]
                    }
                  },
                  "2": { "summary": "Success: No data", "value": { "data": [] } }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": {
                    "summary": "Exception: Invalid path",
                    "value": { "error": "Department must be a number greater than 0" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Not authorized" } }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "error": { "type": "string" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "Department not found" } }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "",
                  "type": "object",
                  "properties": { "error": { "type": "string", "description": "Error message" } },
                  "required": ["error"]
                },
                "examples": {
                  "1": { "summary": "Exception", "value": { "error": "SERVER ERROR" } }
                }
              }
            }
          }
        },
        "security": [{ "bearer": [] }]
      }
    }
  },
  "components": {
    "schemas": {
      "Employee": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" },
          "name": { "type": "string" },
          "lastName": { "type": "string" },
          "birthDate": { "type": "string" },
          "address": { "type": ["string", "null"] },
          "phone": { "type": ["string", "null"] }
        },
        "required": ["id", "name", "lastName", "birthDate", "address", "phone"]
      },
      "Department": {
        "type": "object",
        "properties": {
          "id": { "type": "integer" },
          "name": { "type": "string" },
          "description": { "type": ["string", "null"] }
        },
        "required": ["id", "name", "description"]
      }
    },
    "securitySchemes": { "bearer": { "type": "http", "scheme": "bearer" } }
  },
  "servers": []
}
